// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLbzs-vcqasnzcUivpdG6oerjCcXKpass',
    appId: '1:1009391098184:web:8e41cd7797bf70e7ff3b7d',
    messagingSenderId: '1009391098184',
    projectId: 'notes-a4951',
    authDomain: 'notes-a4951.firebaseapp.com',
    storageBucket: 'notes-a4951.firebasestorage.app',
    measurementId: 'G-4ZL3W7YJ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-q3Sv7LgPnJQJ-SjAL4XKLmV_BjTlkr0',
    appId: '1:1009391098184:android:46ebff70009ec22dff3b7d',
    messagingSenderId: '1009391098184',
    projectId: 'notes-a4951',
    storageBucket: 'notes-a4951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDsDKi2IZzvCF5UjB3wS9NvA9F_kVpgfw',
    appId: '1:1009391098184:ios:f816ccf5fede4fabff3b7d',
    messagingSenderId: '1009391098184',
    projectId: 'notes-a4951',
    storageBucket: 'notes-a4951.firebasestorage.app',
    androidClientId: '1009391098184-d33lvj6rimhppame8o8aktisojoihthc.apps.googleusercontent.com',
    iosClientId: '1009391098184-n22jv6d81hi3frdumh90f5bm0b25vnot.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCantila',
  );
}
